.PHONY: clean All

All:
	@echo "----------Building project:[ challenge-1 - Debug ]----------"
	@cd "challenge-1" && "$(MAKE)" -f  "challenge-1.mk"
clean:
	@echo "----------Cleaning project:[ challenge-1 - Debug ]----------"
	@cd "challenge-1" && "$(MAKE)" -f  "challenge-1.mk" clean
