.PHONY: clean All

All:
	@echo "----------Building project:[ project-2 - Debug ]----------"
	@cd "project-2" && "$(MAKE)" -f  "project-2.mk"
clean:
	@echo "----------Cleaning project:[ project-2 - Debug ]----------"
	@cd "project-2" && "$(MAKE)" -f  "project-2.mk" clean
